### ISSUE TITLE
Поддержка старой версии

### ISSUE THREAD

**Issue by panason** [wb-adegtyarev/telegram2wb#2]
Возможна ли поддержка старой версии движка Version: 1.7.1?
При попытке загрузить правило пишет WARN

```
Nov 17 23:31:50 wirenboard-AEUQHNW4 wb-rules[26493]: INFO: reloading file: /etc/wb-rules/telegram2wb.js
Nov 17 23:31:52 wirenboard-AEUQHNW4 wb-rules[26493]: WARNING: warning: failed to load /etc/wb-rules/telegram2wb.js: ReferenceError: identifier 'exports' undefined
        duk_js_var.c:1232
        anon /etc/wb-rules/telegram2wb.js:657 preventsyield
```

**Comment by aadegtyarev** [comment]
Я 1.7.1 не использую, поэтому сам делать не буду, но подскажу, что не так.

В wb-rules 1.7.1 не было модулей, поэтому ругается.

Можете попробовать сделать модуль скриптом, убрать в конце esports и переписать пример без использования модуля: то есть у вас не будет части про подключение модуля и всё, что с ним связано, например, топики вам надо будет указать вручную.
